// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateCheckResult>;

export function CloseWindow():Promise<void>;

export function DownloadAndRunUpdate(arg1:string):Promise<string>;

export function FetchDashboardData():Promise<main.DashboardData>;

export function GeocodeAddress(arg1:string):Promise<main.Coords>;

export function GetAppVersion():Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetCustomBackgroundURL(arg1:string):Promise<string>;

export function GetNeisAPIKey():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenDownloadURL(arg1:string):Promise<void>;

export function PickAlarmFile():Promise<main.AlarmFileResult>;

export function PickBackgroundFile():Promise<main.BackgroundFileResult>;

export function RemoveCustomBackground(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SearchSchool(arg1:string):Promise<main.SchoolSearchResult>;

export function SetAutoStart(arg1:boolean):Promise<void>;
